AMQP_URI: 'pyamqp://linuxadmin:P@ssw0rd@172.18.21.116'
# AMQP_URI: ${AMQP_URI}
ORACLE_CONFIG:
  host: 'idamdeviusr01'
  instance: "xe"
  username: 'roma'
  password: 'password'

LOGGING:
  version: 1

  formatters:
    brief:
      format: '%(asctime)s %(message)s'
      default_msec_format: '%s.%03d'
      # datefmt: '%Y-%m-%d %H:%M:%S'

  handlers:
    console:
      class: logging.StreamHandler
      formatter: brief
  
  root:
    level: INFO
    handlers: [console]